services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: lenhatthanh
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: